name: Release

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    uses: ./.github/workflows/unit-test.yaml

  integration-test:
    uses: ./.github/workflows/integration-test.yaml

  release:
    runs-on: ubuntu-latest
    needs:
      - unit-test
      - integration-test

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Parse CHANGELOG.md
        uses: mindsers/changelog-reader-action@v2
        id: changelog
        with:
          validation_level: warn

      - name: Determine major version
        uses: actions/github-script@v9
        id: major-version
        with:
          script: |
            const version = "${{ steps.changelog.outputs.version }}";
            return version.split(".")[0];
          result-encoding: "string"

      - name: Push granular release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "v${{ steps.changelog.outputs.version }}"
          name: "v${{ steps.changelog.outputs.version }}"
          body: ${{ steps.changelog.outputs.changes }}
          make_latest: false

      - name: Push major version release
        uses: softprops/action-gh-release@v3
        id: major-release
        with:
          tag_name: "v${{ steps.major-version.outputs.result }}"
          name: "v${{ steps.major-version.outputs.result }}"
          body: ${{ steps.changelog.outputs.changes }}
          make_latest: true

      # softprops/action-gh-release won't update the release tag if a release was already created
      - name: Bump major tag
        uses: actions/github-script@v9
        with:
          script: |
            const version = "${{ steps.changelog.outputs.version }}";
            const majorVersion = version.split(".")[0];
            const ref = `tags/v${majorVersion}`;
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref,
              sha: context.sha
            });
